AWSTemplateFormatVersion: 2010-09-09
Description: "Infra for running auction mark on a throwaway amazon-linux ec2 peer node, destroy at will!"
Parameters:
  EbsOptimised:
    Type: String
    Default: true
  InstanceType:
    Type: String
    Default: m1.small
  VolumeType:
    Type: String
    Default: gp3
  VolumeSize:
    Type: String
    Default: 32
  SutId:
    Type: String
  BenchmarkId:
    Type: String
  JrePackage:
    Type: String
    Default: java-17-amazon-corretto-headless
  JarUrl:
    Type: String
Resources:
  BenchInstance:
    Type: AWS::EC2::Instance
    Properties:
      EbsOptimized: !Ref EbsOptimised
      ImageId: ""
      InstanceType: !Ref InstanceType
      Tags: [benchmark, !BenchmarkId, !Ref SutId]
      BlockDeviceMappings:
        # todo check path of root device on new new ami
        - DeviceName: /dev/xvda/
          Ebs:
            VolumeType: !Ref VolumeType
            VolumeSize: !Ref VolumeSize
            DeleteOnTermination: true

      # todo get script + uberjar + jvm + whatever the hell else you need?
      # use SutId to fetch amazon-linux2 init script from s3? sec, no networking or vpc - we good?!
      # script can then do the rest of the stuff
