AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 compute for xtdb2 testing, see aws-dev-node.clj
Parameters:
  NodeId:
    Description: The unique id of the node
    Type: String
    AllowedPattern: '[-a-zA-Z0-9]+'
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m7gd.medium
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceAMI:
    Description: Managed AMI ID for EC2 Instance
    Type : String
    Default: ami-0530eee00f3a51ab6
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Outputs:
  PublicDnsName:
    Value: !GetAtt [EC2Instance, PublicDnsName]
  KeyPairId:
    Value: !GetAtt [EC2KeyPair, KeyPairId]
  RoleName:
    Value: !Ref EC2Role
Resources:
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Ref NodeId
      Path: /
      Roles:
        - !Ref EC2Role
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref NodeId
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        !Ref InstanceType
      IamInstanceProfile:
        !Ref EC2InstanceProfile
      KeyName:
        !Ref EC2KeyPair
      ImageId:
        !Ref InstanceAMI
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 100
            DeleteOnTermination: true
            Encrypted: false
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:
            !Ref SSHLocation
