AWSTemplateFormatVersion: '2010-09-09'
Description: ec2 env for xtdb oltp+ benchmarks (b2)
Parameters:
  BenchmarkId:
    Description: The unique id of the benchmark run
    Type: String
    AllowedPattern: '[-a-zA-Z0-9]+'
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m1.small
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceAMI:
    Description: Managed AMI ID for EC2 Instance
    Type : String
    Default: ami-0ee415e1b8b71305f
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Outputs:
  PublicDnsName:
    Value: !GetAtt [EC2Instance, PublicDnsName]
  KeyPairId:
    Value: !GetAtt [EC2KeyPair, KeyPairId]
Resources:
  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - xtdb-bench-b2-ec2-role
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref BenchmarkId
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        !Ref InstanceType
      IamInstanceProfile:
        !Ref EC2InstanceProfile
      KeyName:
        !Ref EC2KeyPair
      ImageId:
        !Ref InstanceAMI
      SecurityGroups:
        - !Ref InstanceSecurityGroup
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:
            !Ref SSHLocation
